// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YMart.Data;

#nullable disable

namespace YMart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203145636_initial-febuary")]
    partial class initialfebuary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YMart.Data.Models.Brochure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brochure");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b5df7bd-3654-4879-b9b2-4d9b98fea8fd"),
                            ImageURL = "https://cdn.dribbble.com/userupload/33482357/file/original-b0a2c3498d5afb8ebb87326104c4bcc2.jpg",
                            IsActive = true,
                            ProductNames = "[\"\\u0413\\u0435\\u0439\\u043C\\u0438\\u043D\\u0433 \\u043A\\u043E\\u043C\\u043F\\u043B\\u0435\\u043A\\u0442 \\u043C\\u0438\\u0448\\u043A\\u0430/\\u043F\\u043E\\u0434\\u043B\\u043E\\u0436\\u043A\\u0430 Redragon\",\"Table\",\"Gamer Hoodie\",\"Desk\"]"
                        },
                        new
                        {
                            Id = new Guid("c9dda83d-c8c9-47ee-8e20-f5c892f2043d"),
                            ImageURL = "https://img.freepik.com/free-vector/gradient-gaming-setup-brochure_23-2149833246.jpg?semt=ais_items_boosted&w=740",
                            IsActive = true,
                            ProductNames = "[\"Gamer Hoodie\",\"Logitech H390 Wired Headset for PC/Laptop\",\"Logitech K120 Wired Keyboard for Windows\"]"
                        });
                });

            modelBuilder.Entity("YMart.Data.Models.Cart", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("YMart.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemPrices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemQuantities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YMart.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cc4f639-3036-4548-9c22-0df3491ff635"),
                            Category = "Tech",
                            Description = "Комплектът Redragon M601-BA включва уникални по рода си геймърска мишка и подложка, в тематична Redragon тема, предлагащи ви стила и функционалността, които ще издигнат гейминга ви на изцяло ново, по-добро ниво.",
                            DiscountPercentage = 10.00m,
                            ImageURL = "https://cdn.ozone.bg/media/catalog/product/cache/1/image/a4e40ebdc3e371adff845072e1c73f37/4/6/9bc828752ec7732bed4fe7d0e5ddf742/geyming-komplekt-mishka-i-podlozhka-redragon---m601-ba--cheren-31.jpg",
                            IsDeleted = false,
                            IsOnSale = true,
                            Name = "Гейминг комплект мишка/подложка Redragon",
                            Price = 22.50m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("6acbbde1-5929-43c0-9a72-4f18b07e3f3d"),
                            Category = "Sports",
                            Description = "A football meant for children , for an easier time playing football",
                            ImageURL = "https://m.media-amazon.com/images/I/51rCXKaVGTL.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Beginner Football for kids",
                            Price = 12.00m,
                            Quantity = 105
                        },
                        new
                        {
                            Id = new Guid("cb587e4d-a525-4d8d-814d-6c155182ec30"),
                            Category = "Furniture",
                            Description = "A normal table for your home",
                            DiscountPercentage = 25.00m,
                            ImageURL = "https://images.thdstatic.com/productImages/1c654fe6-311b-4755-b501-a861c534988f/svn/brown-byblight-kitchen-dining-tables-bb-f1889yf-64_600.jpg",
                            IsDeleted = false,
                            IsOnSale = true,
                            Name = "Table",
                            Price = 65.00m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("1462d7c3-6736-403c-965f-7d899ec21ca1"),
                            Category = "Clothing",
                            Description = "A stylish gamer hoodie for devout gamers to wear when going out.",
                            DiscountPercentage = 15.00m,
                            ImageURL = "https://5hourenergy.com/cdn/shop/files/Gamer_Hoodie.jpg?v=1738188168",
                            IsDeleted = false,
                            IsOnSale = true,
                            Name = "Gamer Hoodie",
                            Price = 44.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("7203c3c8-9a31-420f-a50d-82f203b3d40e"),
                            Category = "Tech",
                            Description = "Asus TUF A15 FA506NC-HN012 е висококачествен гейминг лаптоп, комбиниращ производителност от AMD Ryzen и NVIDIA GeForce RTX 30, което ви осигурява отлична бързина и мощност. Той има тънък корпус, малки размери и модерен дизайн, които ви позволяват да играете любимите си игри навсякъде и по всяко време. Създаден за сериозни игри и с елегантен стил, TUF Gaming A15 е геймърски лаптоп, пълен с функции и мощност, която ще ви отведе до победа. Графичният процесор GeForce RTX 30-серия осигурява плавен геймплей на дисплей с честота от 144Hz. От своя страна отличният процесор AMD Ryzen е подсилен от подобрено охлаждане, което повишава производителността на процесора и постига тих звук. Дълготрайната батерия, съчетана с военна издръжливост на TUF, ви гарантират най-добрата ви игра навсякъде.",
                            ImageURL = "https://cdn.ozone.bg/media/catalog/product/cache/1/image/a4e40ebdc3e371adff845072e1c73f37/g/e/6a4b9050825639716505394da9d5dfca/geyming-laptop-asus---tuf-a15-fa506nc-hn012--156----ryzen-5--144hz-30.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Гейминг лаптоп ASUS - TUF A15",
                            Price = 720.00m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("0c3fbb68-6ba6-43fa-a9c2-8c1dec5a4097"),
                            Category = "Furniture",
                            Description = "This is an image duplicate for testing purposes",
                            ImageURL = "https://images.thdstatic.com/productImages/1c654fe6-311b-4755-b501-a861c534988f/svn/brown-byblight-kitchen-dining-tables-bb-f1889yf-64_600.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Duplicate Table",
                            Price = 5.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("c81aa4ed-ec46-43aa-90ab-8c3ba87e6d7d"),
                            Category = "Furniture",
                            Description = "A wooden desk suitible for studying or gaming",
                            DiscountPercentage = 50.00m,
                            ImageURL = "https://wwmake.com/cdn/shop/files/MacieDeskWalnutClear_800x.jpg?v=1689075504",
                            IsDeleted = false,
                            IsOnSale = true,
                            Name = "Desk",
                            Price = 160.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("9de4ca2f-9699-4890-b01d-b6d4440eb646"),
                            Category = "Tech",
                            Description = "Digital Stereo Sound: Fine-tuned drivers provide enhanced digital audio for music, calls, meetings and more. Rotating Noise Canceling Mic: Minimizes unwanted background noise for clear conversations; the rotating boom arm can be tucked out of the way when you’re not using it.",
                            ImageURL = "https://m.media-amazon.com/images/I/61jBnY6paeL._AC_SL1500_.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Logitech H390 Wired Headset for PC/Laptop",
                            Price = 15.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("13c865ba-8bc0-49f9-9260-cfe16a93cbb2"),
                            Category = "Tech",
                            Description = "All-day Comfort: The design of this standard keyboard creates a comfortable typing experience thanks to the deep-profile keys and full-size standard layout with F-keys and number pad. Easy to Set-up and Use: Set-up couldn't be easier, you simply plug in this corded keyboard via USB on your desktop or laptop and start using right away without any software installation.",
                            ImageURL = "https://m.media-amazon.com/images/I/61j3wQheLXL._UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Logitech K120 Wired Keyboard for Windows",
                            Price = 12.10m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f70293a9-83ee-4447-b96b-e30dcfbd5310"),
                            Category = "Tech",
                            Description = "Безжична, лека и свръхпрецизна - геймърската мишка White Shark Dagonet е проектирана за онези, които искат да бъдат свободни от кабели, без да жертват производителност. С тегло само 50 грама, тази мишка е едно от най-леките геймърски предложения на пазара, което гарантира бързи и прецизни реакции при всяко движение.",
                            ImageURL = "https://cdn.ozone.bg/media/catalog/product/cache/1/image/a4e40ebdc3e371adff845072e1c73f37/g/e/764b120060ff570da8aba3222224d42b/geyming-mishka-white-shark---dagonet--optichna--bezzhichna--cherna-lilava-30.jpg",
                            IsDeleted = false,
                            IsOnSale = false,
                            Name = "Gaming Mouse White Shark Dagonet",
                            Price = 40.00m,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YMart.Data.Models.Cart", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMart.Data.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YMart.Data.Models.Product", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
